# Generated by Django 3.2.9 on 2021-11-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=40)),
                ('facility', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=40)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('UF', 'User Facility'), ('RD', 'R&D Agreements for Facility Access')], max_length=2)),
                ('link', models.URLField()),
                ('poc_email', models.EmailField(max_length=254)),
                ('poc_phone', models.CharField(max_length=40)),
            ],
        ),
    ]
