# Generated by Django 3.2.9 on 2021-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='poc_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='poc_phone',
            field=models.CharField(default='', max_length=40),
        ),
    ]
