# Generated by Django 3.2.9 on 2021-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20211126_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='poc_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='poc_phone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
