# Generated by Django 3.2.9 on 2021-11-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20211126_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='type',
            field=models.CharField(choices=[('UF', 'User Facility'), ('RD', 'R&D Agreements for Facility Access')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
