# Generated by Django 3.2.9 on 2021-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20211126_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facility',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='laboratory_name',
            field=models.CharField(max_length=80),
        ),
    ]
